#!/bin/bash
# =============================================================================
# lnkact-monitor.sh - ASL3 Link Activity Monitor
# Replaces the broken native lnkactenable/lnkactmacro functionality in ASL3
#
# Author: Larry K. Aycock (N6LKA)
# Date:   March 2026
#
# Logic:
#   - Monitors local RF activity via kerchunk counter from rpt stats
#     (kerchunks only increment on local RF, not linked node activity)
#   - Also monitors a connection log for new node connections to/from NODE;
#     any new connection resets the inactivity timer
#   - If no local RF activity or new connections for INACT_TIMEOUT seconds,
#     plays a warning then runs the configured reset actions
#   - Uses RPT_ALINKS/RPT_NUMALINKS (direct links only) to avoid false triggers
#     from hub-propagated phantom nodes
#   - Optionally skips reset if only PERMANENT_NODES are connected
#   - Supports scheduled blackout windows (no resets during specified hours)
#   - Supports scheduled forced resets at configured times
#   - Tracks daily reset count in the log
#   - Verifies Asterisk is available before each action cycle
#   - Handles connectlog rotation gracefully
#
# Configuration is stored in:
#   /etc/asterisk/scripts/lnkact-monitor.conf
#
# Do NOT edit this file directly. Edit the conf file instead.
# After changing any setting: systemctl restart lnkact-monitor
#
# =============================================================================
# SERVICE COMMANDS:
#   Start:    systemctl start lnkact-monitor
#   Stop:     systemctl stop lnkact-monitor
#   Restart:  systemctl restart lnkact-monitor
#   Status:   systemctl status lnkact-monitor
#   Logs:     journalctl -u lnkact-monitor -f
# =============================================================================

CONF_FILE="/etc/asterisk/scripts/lnkact-monitor.conf"
LOG_TAG="lnkact-monitor"

# --- Logging ---
log() {
    logger -t "$LOG_TAG" "$1"
    echo "$(date '+%Y-%m-%d %H:%M:%S') $1"
}

# =============================================================================
# --- DEFAULT VALUES ---
# These are used if a variable is missing from the conf file.
# New variables added in updates will be appended to the conf file
# automatically on next startup with these defaults.
# =============================================================================
DEFAULT_NODE=""
DEFAULT_INACT_TIMEOUT=3600
DEFAULT_POLL_INTERVAL=2
DEFAULT_WARN_MODE="tts"
DEFAULT_WARN_AUDIO="/etc/asterisk/local/30seconds-reset"
DEFAULT_WARN_TTS_TEXT="Warning! Node connections will reset in 30 seconds."
DEFAULT_WARN_LEAD=30
DEFAULT_WARN_OFFSET_FILE=7
DEFAULT_WARN_OFFSET_TTS=7
DEFAULT_CONNECT_LOG="/var/log/asterisk/connectlog"
DEFAULT_MIN_CONN_DURATION=60
DEFAULT_PERMANENT_NODES=""
DEFAULT_BLACKOUT_START=""
DEFAULT_BLACKOUT_END=""
DEFAULT_SCHEDULED_RESETS=""
DEFAULT_USE_TELEMETRY="yes"
DEFAULT_DISCONNECT_ALL="yes"
DEFAULT_RECONNECT_NODES=""
DEFAULT_ANNOUNCE="yes"
DEFAULT_ANNOUNCE_TEXT="Connection Reset"

# =============================================================================
# --- CONF FILE MANAGEMENT ---
# =============================================================================

# Load conf file or exit if missing
load_conf() {
    if [[ ! -f "$CONF_FILE" ]]; then
        log "ERROR: Configuration file not found: $CONF_FILE"
        log "Run the installer or create the conf file manually."
        exit 1
    fi
    # shellcheck source=/dev/null
    source "$CONF_FILE"
}

# Check for missing variables and append them to conf file with defaults
check_conf_vars() {
    local appended=false

    append_var() {
        local var="$1"
        local default="$2"
        local comment="$3"
        if ! grep -q "^${var}=" "$CONF_FILE" 2>/dev/null; then
            if [[ "$appended" == "false" ]]; then
                echo "" >> "$CONF_FILE"
                echo "# --- NEW variables added by update on $(date '+%Y-%m-%d') ---" >> "$CONF_FILE"
                appended=true
            fi
            echo "# $comment" >> "$CONF_FILE"
            echo "${var}=\"${default}\"" >> "$CONF_FILE"
            log "NEW config variable added: ${var}=\"${default}\" - please review $CONF_FILE"
        fi
    }

    append_var "NODE"              "$DEFAULT_NODE"              "Node number to monitor"
    append_var "INACT_TIMEOUT"     "$DEFAULT_INACT_TIMEOUT"     "Seconds of RF inactivity before reset (3600 = 60 min)"
    append_var "POLL_INTERVAL"     "$DEFAULT_POLL_INTERVAL"     "How often to check activity in seconds"
    append_var "WARN_MODE"         "$DEFAULT_WARN_MODE"         "Warning mode: tts, file, or none"
    append_var "WARN_AUDIO"        "$DEFAULT_WARN_AUDIO"        "Path to pre-recorded warning file (no extension) - used if WARN_MODE=file"
    append_var "WARN_TTS_TEXT"     "$DEFAULT_WARN_TTS_TEXT"     "TTS warning text - used if WARN_MODE=tts"
    append_var "WARN_LEAD"         "$DEFAULT_WARN_LEAD"         "Seconds before reset to play warning"
    append_var "WARN_OFFSET_FILE"  "$DEFAULT_WARN_OFFSET_FILE"  "Extra seconds offset for file playback timing"
    append_var "WARN_OFFSET_TTS"   "$DEFAULT_WARN_OFFSET_TTS"   "Extra seconds offset for TTS processing + playback timing"
    append_var "CONNECT_LOG"       "$DEFAULT_CONNECT_LOG"       "Path to connection log file - leave blank to disable"
    append_var "MIN_CONN_DURATION" "$DEFAULT_MIN_CONN_DURATION" "Minimum connection duration in seconds before resetting timer (0 = disable)"
    append_var "PERMANENT_NODES"   "$DEFAULT_PERMANENT_NODES"   "Space-separated list of always-connected nodes - reset skipped if only these are linked"
    append_var "BLACKOUT_START"    "$DEFAULT_BLACKOUT_START"    "Blackout window start time HH:MM 24hr - leave blank to disable"
    append_var "BLACKOUT_END"      "$DEFAULT_BLACKOUT_END"      "Blackout window end time HH:MM 24hr"
    append_var "SCHEDULED_RESETS"  "$DEFAULT_SCHEDULED_RESETS"  "Space-separated list of HH:MM times to force a reset daily - leave blank to disable"
    append_var "USE_TELEMETRY"     "$DEFAULT_USE_TELEMETRY"     "Wrap reset in telemetry off/on (cop 34/35): yes or no"
    append_var "DISCONNECT_ALL"    "$DEFAULT_DISCONNECT_ALL"    "Disconnect all nodes before reconnecting: yes or no"
    append_var "RECONNECT_NODES"   "$DEFAULT_RECONNECT_NODES"   "Space-separated list of nodes to reconnect after reset"
    append_var "ANNOUNCE"          "$DEFAULT_ANNOUNCE"          "Play TTS announcement after reset: yes or no"
    append_var "ANNOUNCE_TEXT"     "$DEFAULT_ANNOUNCE_TEXT"     "TTS text spoken after reset completes"

    # Re-source conf file if anything was appended
    if [[ "$appended" == "true" ]]; then
        source "$CONF_FILE"
    fi
}

# Validate required variables after loading conf
validate_conf() {
    if [[ -z "$NODE" ]]; then
        log "ERROR: NODE is not set in $CONF_FILE. Cannot start."
        exit 1
    fi
}

# =============================================================================
# --- LOAD AND VALIDATE CONFIGURATION ---
# =============================================================================
load_conf
check_conf_vars
validate_conf

# =============================================================================
# --- RUNTIME STATE ---
# =============================================================================
reset_count=0
reset_count_date=$(date +%Y-%m-%d)

# =============================================================================
# --- FUNCTIONS ---
# =============================================================================

# --- Check if Asterisk is available ---
asterisk_available() {
    asterisk -rx "core show version" > /dev/null 2>&1
}

# --- Get raw variables from ASL3 ---
get_rpt_variables() {
    asterisk -rx "rpt show variables $NODE" 2>/dev/null
}

# --- Get kerchunk counter from rpt stats (local RF only) ---
get_kerchunk_count() {
    asterisk -rx "rpt stats $NODE" 2>/dev/null | grep "Kerchunks today" | grep -o '[0-9]*' | head -1
}

# --- Check if current time is within the blackout window ---
in_blackout() {
    [[ -z "$BLACKOUT_START" || -z "$BLACKOUT_END" ]] && return 1
    local now_hhmm start end
    now_hhmm=$(date +%H:%M)
    start="$BLACKOUT_START"
    end="$BLACKOUT_END"
    if [[ "$start" < "$end" ]]; then
        [[ "$now_hhmm" >= "$start" && "$now_hhmm" < "$end" ]] && return 0
    else
        [[ "$now_hhmm" >= "$start" || "$now_hhmm" < "$end" ]] && return 0
    fi
    return 1
}

# --- Check if current time matches a scheduled reset time ---
is_scheduled_reset_time() {
    [[ -z "$SCHEDULED_RESETS" ]] && return 1
    local now_hhmm
    now_hhmm=$(date +%H:%M)
    for t in $SCHEDULED_RESETS; do
        [[ "$now_hhmm" == "$t" ]] && return 0
    done
    return 1
}

# --- Increment and log daily reset counter ---
log_reset_count() {
    local today
    today=$(date +%Y-%m-%d)
    if [[ "$today" != "$reset_count_date" ]]; then
        reset_count=0
        reset_count_date=$today
    fi
    (( reset_count++ ))
    log "Reset count today: $reset_count"
}

# --- Check if reset should proceed based on connected nodes ---
should_reset() {
    local vars numlinks links others node is_permanent

    if [[ -z "$PERMANENT_NODES" ]]; then
        return 0
    fi

    vars=$(get_rpt_variables)
    numlinks=$(echo "$vars" | grep "RPT_NUMALINKS=" | tr -d ' ' | cut -d'=' -f2)

    if [[ -z "$numlinks" || "$numlinks" -eq 0 ]]; then
        log "No nodes connected - reset will proceed"
        return 0
    fi

    links=$(echo "$vars" | grep "RPT_ALINKS=" | tr -d ' ' | cut -d'=' -f2 | cut -d',' -f2-)

    others=""
    while IFS= read -r node; do
        node=$(echo "$node" | sed 's/[^0-9]//g' | tr -d ' ')
        [[ -z "$node" ]] && continue
        is_permanent=false
        for perm in $PERMANENT_NODES; do
            if [[ "$node" == "$perm" ]]; then
                is_permanent=true
                break
            fi
        done
        if [[ "$is_permanent" == "false" ]]; then
            others="$others $node"
        fi
    done < <(echo "$links" | tr ',' '\n')

    others=$(echo "$others" | tr -s ' ' | sed 's/^ //')

    if [[ -z "$others" ]]; then
        log "Only permanent node(s) connected ($PERMANENT_NODES) - skipping reset"
        return 1
    fi

    log "Non-permanent node(s) connected: $others - reset will proceed"
    return 0
}

# --- Calculate effective warning trigger point ---
get_warn_trigger() {
    case "$WARN_MODE" in
        file) echo $(( WARN_LEAD + WARN_OFFSET_FILE )) ;;
        tts)  echo $(( WARN_LEAD + WARN_OFFSET_TTS ))  ;;
        *)    echo 0 ;;
    esac
}

# --- Play warning ---
play_warning() {
    case "$WARN_MODE" in
        file)
            log "Playing pre-recorded reset warning on node $NODE"
            asterisk -rx "rpt localplay $NODE $WARN_AUDIO" > /dev/null 2>&1
            ;;
        tts)
            log "Playing TTS reset warning on node $NODE"
            asl-tts -n $NODE -t "$WARN_TTS_TEXT" > /dev/null 2>&1
            ;;
    esac
}

# --- Run reset actions ---
run_reset() {
    log "Running reset actions on node $NODE"
    log_reset_count

    if [[ "$USE_TELEMETRY" == "yes" ]]; then
        log "Disabling telemetry"
        asterisk -rx "rpt cmd $NODE cop 34" > /dev/null 2>&1
        sleep 1
    fi

    if [[ "$DISCONNECT_ALL" == "yes" ]]; then
        log "Disconnecting all nodes"
        asterisk -rx "rpt cmd $NODE ilink 6" > /dev/null 2>&1
        sleep 2
    fi

    if [[ -n "$RECONNECT_NODES" ]]; then
        for recon_node in $RECONNECT_NODES; do
            log "Reconnecting to node $recon_node"
            asterisk -rx "rpt fun $NODE *73$recon_node" > /dev/null 2>&1
            sleep 2
        done
    fi

    if [[ "$USE_TELEMETRY" == "yes" ]]; then
        log "Re-enabling telemetry"
        asterisk -rx "rpt cmd $NODE cop 35" > /dev/null 2>&1
    fi

    if [[ "$ANNOUNCE" == "yes" ]]; then
        log "Playing reset announcement"
        asl-tts -n $NODE -t "$ANNOUNCE_TEXT" > /dev/null 2>&1
    fi

    log "Reset complete"
}

# =============================================================================
# --- MAIN LOOP ---
# =============================================================================
log "Link activity monitor started for node $NODE (timeout=${INACT_TIMEOUT}s, poll=${POLL_INTERVAL}s)"
[[ -n "$PERMANENT_NODES" ]]  && log "Permanent node(s): $PERMANENT_NODES"
[[ -n "$RECONNECT_NODES" ]]  && log "Will reconnect to: $RECONNECT_NODES after reset"
[[ -n "$BLACKOUT_START" ]]   && log "Blackout window: ${BLACKOUT_START} - ${BLACKOUT_END}"
[[ -n "$SCHEDULED_RESETS" ]] && log "Scheduled resets: $SCHEDULED_RESETS"
log "Warning mode: $WARN_MODE"

WARN_TRIGGER=$(get_warn_trigger)

last_activity=$(date +%s)
warning_sent=false
blackout_logged=false
last_scheduled_reset=""

last_kerchunks=$(get_kerchunk_count)
log "Initial kerchunk count: $last_kerchunks"

if [[ -n "$CONNECT_LOG" && -f "$CONNECT_LOG" ]]; then
    last_connect_lines=$(grep -c " connected to $NODE\|^$NODE connected " "$CONNECT_LOG" 2>/dev/null)
    last_connect_lines=${last_connect_lines:-0}
    last_connect_inode=$(stat -c '%i' "$CONNECT_LOG" 2>/dev/null)
    log "Initial connection log count: $last_connect_lines"
else
    last_connect_lines=0
    last_connect_inode=""
fi

while true; do
    now=$(date +%s)
    elapsed=$(( now - last_activity ))

    # --- Asterisk availability check ---
    if ! asterisk_available; then
        log "WARNING: Asterisk not responding - skipping cycle"
        sleep 10
        continue
    fi

    # --- Blackout window check ---
    if in_blackout; then
        if [[ "$blackout_logged" == "false" ]]; then
            log "Blackout window active (${BLACKOUT_START}-${BLACKOUT_END}) - resets suppressed"
            blackout_logged=true
        fi
        last_activity=$now
        warning_sent=false
        sleep "$POLL_INTERVAL"
        continue
    else
        blackout_logged=false
    fi

    # --- Scheduled reset check ---
    if [[ -n "$SCHEDULED_RESETS" ]]; then
        cur_hhmm=$(date +%H:%M)
        if is_scheduled_reset_time && [[ "$cur_hhmm" != "$last_scheduled_reset" ]]; then
            log "Scheduled reset triggered at $cur_hhmm"
            last_scheduled_reset=$cur_hhmm
            if [[ "$WARN_MODE" != "none" ]]; then
                play_warning
                sleep "$WARN_LEAD"
            fi
            run_reset
            last_activity=$now
            warning_sent=false
            sleep "$POLL_INTERVAL"
            continue
        fi
    fi

    # --- Check local RF activity via kerchunk counter ---
    cur_kerchunks=$(get_kerchunk_count)

    if [[ "$cur_kerchunks" -gt "$last_kerchunks" ]]; then
        if [[ "$elapsed" -gt 30 ]]; then
            log "Local RF activity detected (kerchunks: $last_kerchunks->$cur_kerchunks) - resetting inactivity timer (was ${elapsed}s)"
        fi
        last_activity=$now
        warning_sent=false
        last_kerchunks=$cur_kerchunks
        sleep "$POLL_INTERVAL"
        continue
    fi

    # Handle midnight counter reset
    if [[ "$cur_kerchunks" -lt "$last_kerchunks" ]]; then
        log "Kerchunk counter reset (midnight rollover) - re-seeding"
        last_kerchunks=$cur_kerchunks
    fi

    # --- Check connection log for new connections to/from NODE ---
    if [[ -n "$CONNECT_LOG" && -f "$CONNECT_LOG" ]]; then

        cur_inode=$(stat -c '%i' "$CONNECT_LOG" 2>/dev/null)
        if [[ -n "$cur_inode" && "$cur_inode" != "$last_connect_inode" ]]; then
            log "Connection log rotation detected - re-seeding line count"
            last_connect_lines=$(grep -c " connected to $NODE\|^$NODE connected " "$CONNECT_LOG" 2>/dev/null)
            last_connect_lines=${last_connect_lines:-0}
            last_connect_inode=$cur_inode
        fi

        cur_connect_lines=$(grep -c " connected to $NODE\|^$NODE connected " "$CONNECT_LOG" 2>/dev/null)
        cur_connect_lines=${cur_connect_lines:-0}

        if [[ "$cur_connect_lines" -gt "$last_connect_lines" ]]; then
            new_conn=$(grep " connected to $NODE\|^$NODE connected " "$CONNECT_LOG" 2>/dev/null | tail -1)

            conn_qualifies=true
            if [[ "$MIN_CONN_DURATION" -gt 0 ]]; then
                conn_time=$(echo "$new_conn" | grep -oP '\d{2}:\d{2}:\d{2} - \d{2}-\d{2}-\d{4}')
                if [[ -n "$conn_time" ]]; then
                    conn_epoch=$(date -d "$(echo "$conn_time" | sed 's/ - / /')" +%s 2>/dev/null)
                    if [[ -n "$conn_epoch" ]]; then
                        conn_age=$(( now - conn_epoch ))
                        if [[ "$conn_age" -lt "$MIN_CONN_DURATION" ]]; then
                            conn_qualifies=false
                        fi
                    fi
                fi
            fi

            last_connect_lines=$cur_connect_lines

            if [[ "$conn_qualifies" == "true" ]]; then
                if [[ "$elapsed" -gt 30 ]]; then
                    log "New connection detected: $new_conn - resetting inactivity timer (was ${elapsed}s)"
                fi
                last_activity=$now
                warning_sent=false
                sleep "$POLL_INTERVAL"
                continue
            else
                log "New connection detected but under MIN_CONN_DURATION (${MIN_CONN_DURATION}s) - not resetting timer"
            fi
        fi
        last_connect_lines=$cur_connect_lines
    fi

    remaining=$(( INACT_TIMEOUT - elapsed ))

    if [[ "$warning_sent" == "true" && "$elapsed" -lt "$INACT_TIMEOUT" ]]; then
        current_poll=2
    else
        current_poll=$POLL_INTERVAL
    fi

    if [[ "$WARN_MODE" != "none" && "$remaining" -le "$WARN_TRIGGER" && "$remaining" -gt 0 && "$warning_sent" == "false" ]]; then
        if should_reset; then
            play_warning
            warning_sent=true
            current_poll=2
        fi
    fi

    if [[ "$elapsed" -ge "$INACT_TIMEOUT" ]]; then
        if should_reset; then
            run_reset
        fi
        last_activity=$now
        warning_sent=false
        current_poll=$POLL_INTERVAL
    fi

    sleep "$current_poll"
done
